services:
  - type: web
    name: ai-route-battle-backend
    env: node
    plan: free
    buildCommand: ./build-render-v2.sh
    startCommand: cd game/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: static
    name: ai-route-battle-frontend
    env: static
    plan: free
    buildCommand: ./build-render-v2.sh
    staticPublishPath: ./game/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html